name: test-build
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: pnpm install --frozen-lockfile
      - run: pnpm run all
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: h3y6e/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ github.event_name != 'pull_request' }}
  prepare-release:
    if: contains(github.ref, 'master')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: pnpm run prepare-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Use personal access token to trigger another workflow.
