name: Check for uncommitted changes
on: workflow_dispatch

jobs:
  uncommitted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.11.0
      - uses: pnpm/action-setup@v4
      - uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - run: pnpm install --frozen-lockfile
      - run: pnpm run release
      - name: check for uncommitted changes
        run: |
          git diff --exit-code --stat -- . ':!node_modules' \
          || (echo "##[error] found changed files after build. please 'pnpm run build && pnpm run format'" \
                   "and check in all changes" \
              && exit 1)
